### ISSUE TITLE
Info via `surround.__version__`

### ISSUE THREAD

**Issue by luisfciencias** [a2i2/surround#119]
Maybe minor but useful:
```
>>> import surround
>>> surround.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'surround' has no attribute '__version__'
```

**Comment by AkshatBajaj** [comment]
Use `pkg_resources.get_distribution("surround").version`

<img width="758" alt="pkg_resources" src="https://user-images.githubusercontent.com/32318980/58394143-1ef6b080-8085-11e9-8c8d-dbf972bdffbb.png">

**or**

`pip3 show surround`

<img width="885" alt="show" src="https://user-images.githubusercontent.com/32318980/58394155-2d44cc80-8085-11e9-8430-11d232bbd879.png">
