### ISSUE TITLE
Data management CLI specification.

### ISSUE THREAD

**Issue by ScottyB** [a2i2/surround#138]
Write a proposal for a data manipulation tool that includes the generation of a schema:

Schema:
- version:  Manifest version
- title
- creator
- subject (classification codes for a controlled vocabulary)
- description (visual/text etc.)
- A: publisher (service or person)
- contributor (possibly list of people)
- A: date (ISO 8601)
- type (one of: http://dublincore.org/documents/2000/07/11/dcmi-type-vocabulary/
- A: format (controlled vocabulary - MIME types)
- A: identifier (hash/sha)
- source (formal identification string CONVENTION)
- A: language (eng)
- A: relation (formal identifier to other resources CONVENTION)
- A: rights
- coverage (controlled vocabulary: named places, time periods)

**Comment by ScottyB** [comment]
Have a look at Pickle, tf record, and [HDF5](https://www.hdfgroup.org/)

Todo:
- Propose conventions for sections above
- Propose rights for the data
- Container format based on zip, `.data`
- Container format is intended to be immutable i.e. Surround tools will not modify contents.

**Comment by ucokzeko** [comment]
Implemented on #164, closing this for now
