### ISSUE TITLE
Running without building

### ISSUE THREAD

**Issue by AkshatBajaj** [a2i2/surround#155]
surround run blah will fail if the user has not build the image. However, the error message is not helpful, it should instead print docker image not found. 

`error: docker image not found`
`Build the image first by running surround run build`

**Comment by Nikhii** [comment]
Hi, Just checked this issue.Can't we just have a task dependency on build task?

**Comment by ucokzeko** [comment]
Just tested the latest version and it seems like this has been addressed

```
➜  test_project surround run batch
.  batch
Unable to find image 'yourcompany/test_project:latest' locally
```
