### ISSUE TITLE
Git Ignore data directory

### ISSUE THREAD

**Issue by AkshatBajaj** [a2i2/surround#156]
At the moment, we add `data/` to project level gitignore.
This results in data directory being ignored by git and will not be present when someone clones the project. Then we have to create this on `surround pull` which can cause issues.

We should instead add gitignore to data dir with the following details:
```
# Ignore everthying in this dir except .gitignore
*
!.gitignore
```
Similar to [surround-paparazzi](https://github.com/AkshatBajaj/surround-paparazzi)

**Comment by ScottyB** [comment]
`surround pull` should result in the `input` folder being created.

**Comment by luisfciencias** [comment]
Related: After generating a surround folder project via `surround init -p foogoo -d "Testing"` the folders `input/` and `output/` are created by default. `input\` is inside the `.gitignore`, do you recommend to do the same with `output/`?

**Comment by ucokzeko** [comment]
Closing this based on this comment https://github.com/a2i2/surround/pull/163#issuecomment-521092446
