### ISSUE TITLE
Hyphen in Project Name

### ISSUE THREAD

**Issue by AkshatBajaj** [a2i2/surround#158]
Ignore hyphen when creating classes from project name.

**Comment by zacbrannelly** [comment]
We don't allow hyphens in project names, only underscores at the moment, and the underscores are removed when used as class names, see this PR #131

**Comment by AkshatBajaj** [comment]
Have you released after merging this PR?
At the moment, surround doesn't throw error if I create project with hyphen.

**Comment by zacbrannelly** [comment]
Nah there hasn't been a release yet, master is about three merged PR's ahead of the last release
