### ISSUE TITLE
Tornado server not working properly

### ISSUE THREAD

**Issue by AkshatBajaj** [a2i2/surround#160]
`python3 -m projectname` works fine
but when using surround run, it does not work

To reproduce the bug:
`surround run dev`
Goto http://localhost:8080/info
It refuses the connection...

**Comment by zacbrannelly** [comment]
You on Windows? Try http://192.168.99.100:8080/info

**Comment by AkshatBajaj** [comment]
On mac....
surround run web is working as expected, however surround run dev is not....
