### ISSUE TITLE
FEATURE REQUEST: Poetry support

### ISSUE THREAD

**Issue by agrantdeakin** [a2i2/surround#280]
https://python-poetry.org/

Poetry brings Gradle-like simplicity to managing Python projects.

- It creates/manages a virtual environment.
- Acts as a dependency manager (no need for `pip`).
- Allows you to `build` and package your app.
- Has a very nice CLI.

It would be great to offer Surround support to generate a project with either `pip` (with `conda`?) or `Poetry` support.

**Comment by ScottyB** [comment]
Thanks for bringing this to our attention. Generated projects use Poetry with #290 and we will update Surround in a future release.
