### ISSUE TITLE
Ordered loading of configuration

### ISSUE THREAD

**Issue by marcotama** [a2i2/surround#58]
This is a feature request for having the order of configuration entries to be preserved.

*The state of things* - Up to 3.6, the Python specification does not give any guarantee on the order keys and values are yielded when a dictionary is iterated over. Since 3.7, the implementation of dictionaries has been changed, and the new one comes with ordering out-of-the-box, which is why the ordering is part of the language specification.

*The motivation* - Data science projects are exploratory in nature. To keep track of what was done across the experiments, my code `yaml.dump`s the configuration in the folder. In the past I had the need to `diff` two configurations. This was only possible because the order of parameters was consistent - otherwise, the `diff` would have been a mess. Not sure if you could output in alphabetical order (it would be consistent), but I argue that that is also not optimal since the configurations are often sorted in a way that makes sense to humans. Therefore, the original order should be maintained. I realise that a copy 1:1 of the file could be made, but I argue that only configuration should be kept, without comments.

*Possible solutions* - Since we cannot always assume the data scientist will be able to use Python 3.7 (for example, a specific library could be required which does not support 3.7), the library should provide (optionally or by default) the behaviour requested. The `oyaml` library wraps the `PyYaml` library, setting it up to use `OrderedDict`s. The library can be installed as easily as `pip install oyaml`. Alternatively, the procedure described in [this StackOverflow thread](https://stackoverflow.com/a/21912744) can be used.

**Comment by ScottyB** [comment]
Closing this issue as we now use https://github.com/mk-fg/pretty-yaml.
